-- AURA V2: Supabase Schema
-- Run this in the Supabase SQL Editor

-- Enable the uuid-ossp extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table: sessions
-- Tracks active user sessions and their chosen mode
CREATE TABLE sessions (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  session_id TEXT UNIQUE NOT NULL,
  mode TEXT NOT NULL,
  preferences JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: plans
-- Tracks the multi-step execution plans generated by the Planner Agent
CREATE TABLE plans (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  session_id TEXT REFERENCES sessions(session_id) ON DELETE CASCADE,
  plan_id TEXT UNIQUE NOT NULL,
  query TEXT NOT NULL,
  mode TEXT NOT NULL,
  steps JSONB NOT NULL,
  current_step_index INTEGER DEFAULT 0,
  status TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: messages
-- Tracks all chat messages for context and history
CREATE TABLE messages (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  session_id TEXT REFERENCES sessions(session_id) ON DELETE CASCADE,
  message_id TEXT UNIQUE NOT NULL,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  plan_id TEXT,
  step_id TEXT,
  is_follow_up BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes for fast querying by session_id
CREATE INDEX idx_messages_session_id ON messages(session_id);
CREATE INDEX idx_plans_session_id ON plans(session_id);

-- Set up Row Level Security (RLS) policies (Optional/Allow all for Hackathon)
-- We enable it but allow anon access for now based on session_id from the frontend
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon read/write sessions" ON sessions FOR ALL USING (true);
CREATE POLICY "Allow anon read/write plans" ON plans FOR ALL USING (true);
CREATE POLICY "Allow anon read/write messages" ON messages FOR ALL USING (true);
